catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import home, contacts, ProductListView, pictures, BlogListView, BlogCreateView, BlogUpdateView, \
    BlogDeleteView, BlogDetailView, change_status, ProductCreateView, ProductDetailView, ProductUpdateView, \
    ProductDeleteView, ProductUpdateWithVersionView

app_name = CatalogConfig.name

urlpatterns = [
    path('', home),
    path('contacts/', contacts),
    path('products/pictures/', pictures),
    path('products/', ProductListView.as_view(), name='product'),
    path('products/create/', ProductCreateView.as_view(), name='create_product'),
    path('products/update/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('products/delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
    path('products/detail/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('products/update/<int:pk>/version/', ProductUpdateWithVersionView.as_view(), name='update_product_version'),
    path('products/blog/', BlogListView.as_view(), name='blog'),
    path('products/blog/create/', BlogCreateView.as_view(), name='create'),
    path('products/blog/update/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('products/blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('products/blog/detail/<int:pk>/', BlogDetailView.as_view(), name='detail'),
    path('products/blog/status/<int:pk>/', change_status, name='status')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
    path('verification/', include('verify_email.urls')),
    path('users/', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
import django
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.contrib.auth import views as auth_views
from users.apps import UsersConfig
from users.views import CustomLoginView, UserEditProfileView, CustomRegisterView, ActivateAccount

app_name = UsersConfig.name

urlpatterns = [
    path('', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', UserEditProfileView.as_view(), name='profile'),
    path('register/', CustomRegisterView.as_view(), name='register'),
    path('activate/<uidb64>/<token>/', ActivateAccount.as_view(), name='activate'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html',
             subject_template_name='users/password_reset_subject.txt',
             email_template_name='users/password_reset_email.html',
             success_url='done/'
         ),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password_reset_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete')
]

catalog/models.py
from django.db import models
from django.utils.text import slugify

from config import settings
from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Product(models.Model):
    product_name = models.CharField(max_length=250, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='media/', verbose_name='Изображение (превью)', **NULLABLE)
    category = models.CharField(max_length=250, verbose_name='Категория')
    price = models.FloatField(verbose_name='Цена за покупку')
    creation_date = models.DateTimeField(verbose_name='Дата создания')
    date_of_update = models.DateTimeField(verbose_name='Дата последнего изменения')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    sign_of_publication = models.BooleanField(default=False, verbose_name='признак публикации')

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        permissions = [
            ('set_sign_of_publication', 'Can cancel product publication'),
            ('change_description_product', 'Can change product description'),
            ('change_category_product', 'Can change product category')

        ]


class Category(models.Model):
    category_name = models.CharField(max_length=250, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return f'{self.category_name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Blog(models.Model):
    STATUS_ACTIVE = 'active'
    STATUS_INACTIVE = 'inactive'
    STATUSES = (
        ('active', 'Опубликованный'),
        ('inactive', 'Не опубликованный'),
    )

    head = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.CharField(max_length=250, verbose_name='Slug')
    content = models.TextField(verbose_name='Содержимое')
    image = models.ImageField(upload_to='media/', verbose_name='Изображение(превью)', **NULLABLE)
    creation_date = models.DateTimeField(verbose_name='Дата создания')
    sign_of_publication = models.CharField(choices=STATUSES, default=STATUS_ACTIVE, max_length=250, verbose_name='Признак публикации')
    views_number = models.IntegerField(default=0, verbose_name='Количество просмотров')

    def save(self, *args, **kwargs):
        self.slug = slugify(self.head)
        super(Blog, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'


class Version(models.Model):
    STATUS_ACTIVE = 'active'
    STATUS_INACTIVE = 'inactive'
    STATUSES = (
        ('active', 'активная'),
        ('inactive', 'неактивная')
    )
    product = models.ForeignKey(Product, verbose_name='Продукт', on_delete=models.CASCADE)
    number = models.FloatField(default=1, verbose_name='Номер версии')
    name = models.CharField(max_length=250, verbose_name='Название версии')
    status = models.CharField(choices=STATUSES, default=STATUS_INACTIVE, max_length=50, verbose_name='Признак текущей версии')

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        exclude = ['user_create']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def clean(self):
        cleaned_data = super().clean()
        allowed_name = cleaned_data.get('product_name')
        allowed_description = cleaned_data.get('description')
        if allowed_name and allowed_description:
            if ('казино' or 'криптовалюта'or 'крипта' or 'биржа' or 'дешево' or 'бесплатно'or 'обман'or 'полиция'or 'радар') in (allowed_name and allowed_description):
                raise forms.ValidationError('Название и описание не должны содержать запрещенных слов')
        return cleaned_data


class VersionForm(forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db import transaction
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.urls import reverse_lazy, reverse

from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Blog, Version
from catalog.services import cache_category


def home(request):
    return render(request, 'catalog/home.html')


def contacts(request):
    return render(request, 'catalog/contacts.html')


def pictures(request):
    context = {
        'object_list': Product.objects.all()
    }
    return render(request, 'catalog/pictures.html', context)


class ProductListView(ListView):
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['category'] = cache_category(self)
        return context_data


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product')
    raise_exception = True
    permission_denied_message = "Access is restricted to authenticated users"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user_create = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class ProductUpdateView(UserPassesTestMixin, LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product')
    raise_exception = True
    permission_denied_message = "Access is restricted to authenticated users"

    def get_queryset(self):
        return Product.objects.filter(user_create=self.request.user)

    def test_func(self):
        product = self.get_object()
        return product.user_create == self.request.user or self.request.user.has_perms(
            perm_list=['set_sign_of_publication', 'change_description_product', 'change_category_product'])


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:product')
    raise_exception = True
    permission_denied_message = "Access is restricted to authenticated users"


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    raise_exception = True
    permission_denied_message = "Access is restricted to authenticated users"


class ProductUpdateWithVersionView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product')
    template_name = 'catalog/product_with_version.html'
    raise_exception = True
    permission_denied_message = "Access is restricted to authenticated users"

    def get_success_url(self):
        return reverse('catalog:product_detail', args=[self.object.pk])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        FormSet = inlineformset_factory(self.model, Version, form=VersionForm, extra=1)

        if self.request.method == 'POST':
            formset = FormSet(self.request.POST, instance=self.object)
        else:
            formset = FormSet(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        print(self.request.method)
        with transaction.atomic():
            self.object = form.save()
            if formset.is_valid():
                formset.instance = self.object
                formset.save()
        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(sign_of_publication=Blog.STATUS_ACTIVE)

        return queryset


class BlogCreateView(CreateView):
    model = Blog
    fields = '__all__'
    success_url = reverse_lazy('catalog:blog')


class BlogUpdateView(UpdateView):
    model = Blog
    fields = '__all__'
    success_url = reverse_lazy('catalog:blog')


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('catalog:blog')


class BlogDetailView(DetailView):
    model = Blog

    def get(self, request, pk):
        blog_item = get_object_or_404(Blog, pk=pk)
        blog_item.views_number += 1
        blog_item.save()
        return super().get(self, request, pk)


def change_status(request, pk):
    blog_item = get_object_or_404(Blog, pk=pk)
    if blog_item.sign_of_publication == Blog.STATUS_ACTIVE:
        blog_item.sign_of_publication = Blog.STATUS_INACTIVE
    else:
        blog_item.sign_of_publication = Blog.STATUS_ACTIVE
    blog_item.save()

    return redirect(reverse('catalog:blog'))

catalog/templates/catalog/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
{% include 'catalog/includes/main_menu.html' %}
<div class="container">
    {% block content %}
    {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <a href="{% url 'catalog:blog' %}">Отмена</a>
                        <button type="submit">Удалить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Заголовок</td>
                            <td>{{ object.head }}</td>
                        </tr>
                        <tr>
                            <td>Slug</td>
                            <td>{{ object.slug }}</td>
                        </tr>
                        <tr>
                            <td>Content</td>
                            <td>{{ object.content }}</td>
                        </tr>
                        <tr>
                            <td>Изображение (превью)</td>
                            <td>{{ object.image }}</td>
                        </tr>
                        <tr>
                            <td>Дата создания</td>
                            <td>{{ object.creation_date }}</td>
                        </tr>
                        <tr>
                            <td>Признак публикации</td>
                            <td>{{ object.sign_of_publication }}</td>
                        </tr>
                        <tr>
                            <td>Кол-во просмотров</td>
                            <td>{{ object.views_number }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit">Сохранить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html' %}

{% block content %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Заголовок</th>
            <th scope="col">Slug</th>
            <th scope="col">Содержимое</th>
            <th scope="col">Изображение (превью)</th>
            <th scope="col">Дата создания</th>
            <th scope="col">Признак публикации</th>
            <th scope="col">Кол-во просмотров</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr>
                <td>
                    <a href="{% url 'catalog:detail' object.pk %}">
                        #{{ object.pk }}
                    </a>
                </td>
                <td>{{ object.head }}</td>
                <td>{{ object.slug }}</td>
                <td>{{ object.content }}</td>
                <td>
                    <img src="/media/{{ object.image }}" alt="" border=3 height=100 width=150></img>
                </td>
                <td>{{ object.creation_date }}</td>
                <td>{{ object.get_sign_of_publication_display }}
                    {% if object.sign_of_publication == 'active' %}
                        <a class="btn btn-danger" href="{% url 'catalog:status' object.pk %}">Inactive</a>
                    {% else %}
                        <a class="btn btn-info" href="{% url 'catalog:status' object.pk %}">Active</a>
                    {% endif %}
                </td>
                <td>{{ object.views_number }}</td>
                <td>
                    <a class="btn btn-info" href="{% url 'catalog:update' object.pk %}">Update</a>
                    <a class="btn btn-danger" href="{% url 'catalog:delete' object.pk %}">Delete</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

catalog/templates/catalog/contacts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                    </form>
                    <input type="submit">
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/home.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
{#    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">#}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/products/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Удобный сервис рассылок</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">$ 140</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- Неограниченная лицензия</li>
                        <li>- Поддержка</li>
                        <li>- Установка на сервер</li>
                        <li>- Получение обновлений</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/pictures.html
{% extends 'catalog/base.html' %}
{% load mediapath from template_filters %}
{% block content %}
 <div class="container">
  <div class="card">
    {% for object in object_list %}
    <div class="photo">
        <img src="{% mediapath object.image %}" alt="" border=5 height=200 width=300>
    </div>
  </div>
 </div>
    {% endfor%}

{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <a href="{% url 'catalog:product' %}">Отмена</a>
                        <button type="submit">Удалить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit">Сохранить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load mediapath from template_filters %}
{% block content %}
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-primery border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Магазин</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-info" href="{% url 'catalog:create_product' %}">Создать продукт</a>
    </nav>
</div>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Наименование</th>
            <th scope="col">Описание</th>
            <th scope="col">Изображение (превью)</th>
            <th scope="col">Категория</th>
            <th scope="col">Цена</th>
            <th scope="col">Дата создания</th>
            <th scope="col">Дата последнего изменения</th>
            <th scope="col">Версия</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr>
                <td>
                    <a href="{% url 'catalog:product_detail' object.pk %}">
                        #{{ object.pk }}
                    </a>
                </td>
                <td>{{ object.product_name }}</td>
                <td>{{ object.description|truncatechars:100 }}</td>
                <td><img src="{% mediapath object.image %}" alt="" border=5 height=200 width=300></td>
                <td>{{ object.category }}</td>
                <td>{{ object.price }}</td>
                <td>{{ object.creation_date }}</td>
                <td>{{ object.date_of_update }}</td>
                <td>{{ object.Version.product_id }}</td>
                <td>
                    <a class="btn btn-info" href="{% url 'catalog:update_product_version' object.pk %}">Update Version</a>
                    <a class="btn btn-danger" href="{% url 'catalog:delete_product' object.pk %}">Delete</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

catalog/templates/catalog/products.html
{% extends 'catalog/base.html' %}

{% block content %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Наименование</th>
            <th scope="col">Описание</th>
            <th scope="col">Изображение (превью)</th>
            <th scope="col">Категория</th>
            <th scope="col">Цена</th>
            <th scope="col">Дата создания</th>
            <th scope="col">Дата последнего изменения</th>
        </tr>
        </thead>
        <tbody>
        {% for product in product_list %}
            <tr>
                <td>{{ product.id }}</td>
                <td>{{ product.product_name }}</td>
                <td>{{ product.description|truncatechars:100 }}</td>
                <td>{{ product.image }}</td>
                <td>{{ product.category }}</td>
                <td>{{ product.price }}</td>
                <td>{{ product.creation_date }}</td>
                <td>{{ product.date_of_update }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}